insert into salesb2b.cust_alliance
select at_cd_rec_loc,
       at_seg_seq_nbr,
       at_pax_nbr,
       at_is_cx,
       at_cx_from,
       ca_total_revenue,
       at_cd_airline,
       at_cd_airport_orig,
       at_cd_airport_dest,
       at_placa,
       at_cd_carrier,
       at_cd_airline_oper,
       at_route,
       at_market,
       at_cd_flight_number,
       at_dt_flight,
       at_dt_sale,
       at_family_fare,
       at_ca_ndo,
       at_sales_channel_1,
       at_sales_channel_2,
       at_sales_channel_4,
       at_sales_channel_9,
       at_physical_channel_1,
       at_physical_channel_2,
       at_is_alliance,
       ts_creation,
       ts_modification,
       at_cx_seg_seq_nbr,
       at_cx_carrier,
       at_pnr_nbr_of_pax
--at_dt_booking
from salesb2b.stg_cust_alliance;