with SSR as
(select
	SSR.rec_loc,
	SSR.pax_nbr,
	SSR.seg_seq_nbr,
	SSR.ssr_code
from Vueling_ODS.dbo.SEGMENT_SSR SSR
where SSR_code in ('SEUP', 'SBID')
), revenues as -- sacamos precio total
(select distinct
	FS.rec_loc,
	FS.pax_nbr,
	family_fare,
	sum(coalesce(cdiscount, 0) + coalesce(reparto_Fees, 0)) as Ticket_rev,
	sum(coalesce(cdiscount, 0) + coalesce(reparto_Fees, 0) + coalesce(tax_1, 0) + coalesce(tax_2, 0) + coalesce(tax_3, 0) + coalesce(tax_4, 0) + coalesce(tax_5, 0) + coalesce(tax_6, 0) + coalesce(AnciRev, 0)) as Total_price
from vueling_calcods.dbo.factsegment FS
	left join ( select
					fee.AT_CD_PNR,
					fee.AT_CD_PAX_NBR,
					fee.AT_CD_SEG_SEQ_NBR,
					sum(fee.MT_COMPANY_BASE_AMOUNT) AS AnciRev
				from vueling_calcods.fees.FACT_FEE fee
						inner join Vueling_data_master.dbo.DIM_FEE_TYPE dft on dft.ID_FEE_TYPE = fee.ID_FEE_TYPE
				where dft.AT_DS_REVENUE_CONCEPT_1 in ('ANCILLARY','ANCILIARY','3RD PARTY ANCILIARY')
					and fee.AT_IS_AUTOGENERATED_FEE = 0
					and fee.OT_DT_END_DATE = '29991231'
				group by fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR) FEE on fee.AT_CD_PNR = fs.rec_loc
																					and fee.AT_CD_PAX_NBR = fs.pax_nbr
																					and fee.AT_CD_SEG_SEQ_NBR = fs.seg_seq_nbr
group by
	FS.rec_loc,
	FS.pax_nbr,
	family_fare
), vuelos as
(select
	FS.rec_loc,
	FS.pax_nbr,
	FS.seg_seq_nbr,
	cast(FF.Flight_date as date) as Flight_date,
	FF.route,
	FF.Flight_number
from vueling_calcods.dbo.factsegment FS
	inner join vueling_calcods.dbo.factflight FF on FF.flight_sk = FS.flight_sk
	inner join Vueling_ODS.dbo.SEGMENT_SSR SSR on SSR.rec_loc = FS.rec_loc
													and SSR.PAX_NBR = FS.pax_nbr
													and SSR.seg_seq_nbr = FS.seg_seq_nbr
													and ssr_code in ('SEUP', 'SBID')
),asientos_gratuitos as -- sacamos los asientos gratuitos que no tienen fee
(select
	PL.rec_loc,
	PL.PAX_NBR,
	PL.seg_seq_nbr,
	seat_nbr
from Vueling_ODS.dbo.PAX_LEG PL
	inner join Vueling_ODS.dbo.SEGMENT_SSR SSR on SSR.rec_loc = PL.rec_loc
													and SSR.PAX_NBR = PL.pax_nbr
													and SSR.seg_seq_nbr = PL.seg_seq_nbr
where
	SSR_code in ('SEUP', 'SBID')
), asientos_fee as -- sacamos los asientos que si tienen fee y su rev de ancillary
(select distinct
	fee.AT_CD_PNR,
	fee.AT_CD_PAX_NBR,
	fee.AT_CD_SEG_SEQ_NBR,
	fee.at_flight_number,
	fee.OT_DT_END_DATE,
	max(fee.OT_DT_START_DATE) as max_date,
	fee.at_seat_nbr,
	dft.AT_DS_REVENUE_CONCEPT_3,
	sum(fee.MT_COMPANY_BASE_AMOUNT) AS AnciRev
from vueling_calcods.fees.FACT_FEE fee
	inner join Vueling_data_master.dbo.DIM_FEE_TYPE dft on dft.ID_FEE_TYPE = fee.ID_FEE_TYPE
	inner join Vueling_ODS.dbo.SEGMENT_SSR SSR on SSR.rec_loc = FEE.at_cd_pnr
													and SSR.PAX_NBR = FEE.at_cd_pax_nbr
													and SSR.seg_seq_nbr = FEE.at_cd_seg_seq_nbr
	inner join VUELING_CALCODS.dbo.factsegment FS on FS.rec_loc = FEE.at_cd_pnr
													and FS.PAX_NBR = FEE.at_cd_pax_nbr
													and FS.seg_seq_nbr = FEE.at_cd_seg_seq_nbr
	inner join vueling_calcods.dbo.factflight FF on FF.flight_sk = FS.flight_sk
													and FF.flight_number = fee.at_flight_number -- se pone este filtro porque hay pnrs que no entran bien, ejemplo VG84KP
where dft.at_cd_service_type like '%SEAT%'
	and SSR_code in ('SEUP', 'SBID')
group by
	fee.AT_CD_PNR,
	fee.AT_CD_PAX_NBR,
	fee.AT_CD_SEG_SEQ_NBR,
	fee.at_flight_number,
	fee.OT_DT_END_DATE,
	fee.at_seat_nbr,
	dft.AT_DS_REVENUE_CONCEPT_3
), bundle as -- sacamos los bundles que tiene el PNR que ha utilizado ssr SEUP y SBID
(select distinct
	fee.AT_CD_PNR,
	fee.AT_CD_PAX_NBR,
	fee.AT_CD_SEG_SEQ_NBR,
	case when FEE.AT_IS_BUNDLE is null then 'N' else 'Y' end as is_Bundle,
	dft.AT_CD_SERVICE_TYPE,
	fee.MT_COMPANY_BASE_AMOUNT as AnciRev
from vueling_calcods.fees.FACT_FEE fee
	inner join Vueling_data_master.dbo.DIM_FEE_TYPE dft on dft.ID_FEE_TYPE = fee.ID_FEE_TYPE
	inner join Vueling_ODS.dbo.SEGMENT_SSR SSR on SSR.rec_loc = FEE.at_cd_pnr
													and SSR.PAX_NBR = FEE.at_cd_pax_nbr
													and SSR.seg_seq_nbr = FEE.at_cd_seg_seq_nbr
where at_ds_revenue_concept_2 in ('BUNDLE', 'Bundle')
	and ssr_code in ('SEUP', 'SBID')
)
select distinct
	SSR.ssr_code as SSR,
	SSR.rec_loc as PNR,
	SSR.pax_nbr as Pax_nbr,
	case when asientos_fee.OT_DT_END_DATE < '29991231' and asientos_fee.AT_DS_REVENUE_CONCEPT_3 like '%SEAT%' then asientos_fee.at_seat_nbr
		when asientos_fee.OT_DT_END_DATE = '29991231' and asientos_fee.AT_DS_REVENUE_CONCEPT_3 like '%SEAT%' then asientos_fee.at_seat_nbr
		when asientos_fee.AT_DS_REVENUE_CONCEPT_3 not like '%SEAT%' then asientos_gratuitos.seat_nbr
		when asientos_fee.at_cd_pnr is null then asientos_gratuitos.seat_nbr else ''
	end as seat_nbr,
	case when asientos_fee.OT_DT_END_DATE < '29991231' and asientos_fee.AT_DS_REVENUE_CONCEPT_3 like '%SEAT%' then 'Asiento inicial'
		when asientos_fee.OT_DT_END_DATE = '29991231' and asientos_fee.AT_DS_REVENUE_CONCEPT_3 like '%SEAT%' then 'Asiento final'
		when asientos_fee.AT_DS_REVENUE_CONCEPT_3 not like '%SEAT%' then asientos_gratuitos.seat_nbr
		when asientos_fee.at_cd_pnr is null then 'Asiento final' else ''
	end as seat_type,
	asientos_fee.AT_DS_REVENUE_CONCEPT_3 as Revenue_concept_3,
	asientos_fee.AnciRev as Ancillary_rev_seat,
	revenues.Ticket_rev,
	revenues.total_price,
	bundle.is_Bundle,
	bundle.AT_CD_SERVICE_TYPE as Bundle_code,
	bundle.AnciRev as Bundle_rev,
	vuelos.Flight_date as [Flight Date],
	vuelos.route as segment,
	vuelos.Flight_number as Flight_number,
	revenues.family_fare as Family_fare
from
	SSR
		inner join revenues on revenues.rec_loc = SSR.rec_loc
								and revenues.pax_nbr = SSR.pax_nbr
		left join asientos_gratuitos on asientos_gratuitos.rec_loc = revenues.rec_loc
										and asientos_gratuitos.pax_nbr = revenues.pax_nbr
										and asientos_gratuitos.seg_seq_nbr = SSR.seg_seq_nbr
		left join asientos_fee on asientos_fee.at_cd_pnr = revenues.rec_loc
									and asientos_fee.at_cd_pax_nbr = revenues.pax_nbr
									and asientos_fee.at_cd_seg_seq_nbr = SSR.seg_seq_nbr
		left join bundle on bundle.at_cd_pnr = revenues.rec_loc
							  and bundle.at_cd_pax_nbr = revenues.pax_nbr
							  and bundle.at_cd_seg_seq_nbr = SSR.seg_seq_nbr
		inner join vuelos on vuelos.rec_loc = SSR.rec_loc
								and vuelos.pax_nbr = SSR.pax_nbr
								and vuelos.seg_seq_nbr = SSR.seg_seq_nbr;

