SELECT
  Table__101.flight_number,
  Table__101.airline_code,
  Table__101.flight_date,
  Table__101.HoraSalida,
  Table__101.HoraLlegada,
  Table__101.airport_orig,
  Table__101.airport_dest,
  Table__101.pnrs,
  Table__101.iata,
  Table__101.nombre_comercial,
  Table__101.tarifa,
  Table__101.totalPax,
  Table__101.paxiata,
  Table__101.seats,
  Table__101.asientosReservados,
  Table__101.CosteTotal,
  Table__101.lf
FROM
  (
  SELECT
	STG.FLIGHT_NUMBER,
	TP.AIRLINE_CODE,
	STG.FLIGHT_DATE,
	STG.HORASALIDA,
	STG.HORALLEGADA,
	STG.AIRPORT_ORIG,
	STG.AIRPORT_DEST,
	STG.PNRS,
	STG.IATA,
	STG.NOMBRE_COMERCIAL,
	TP.TOTALPAX AS TOTALPAX,
	STG.PAX AS PAXIATA,
	STG.SEATS,
	STG.ASIENTOSRESERVADOS,
	STG.PNR_TOTAL AS COSTETOTAL,
	(100*CAST(TP.TOTALPAX AS NUMERIC(18,2))/STG.SEATS) AS LF,
	TP.FARE_BASIS_NAV AS TARIFA
FROM
	VUELING_CALCODS.TTOO.STG_FLIGHT_PNRS_GGROUP STG
 JOIN
	(
		SELECT
			FF.FLIGHT_SK,
			FF.AIRLINE_CODE,
			COUNT(*) AS TOTALPAX,
			FS.FARE_BASIS_NAV
		FROM
			VUELING_CALCODS..FACTFLIGHT FF
		JOIN
			VUELING_CALCODS..FACTSEGMENT FS
			ON
				FF.FLIGHT_SK = FS.FLIGHT_SK
		GROUP BY
			FF.FLIGHT_SK,
			FF.AIRLINE_CODE,
			FS.FARE_BASIS_NAV
	) TP
		ON TP.FLIGHT_SK=STG.FLIGHT_SK AND TP.FARE_BASIS_NAV = STG.FARE_BASIS_NAV
WHERE
	TP.FARE_BASIS_NAV IN ('GROUP','ALLOTGR')
  )  Table__101
