create table salesb2b.stg_cust_alliance
(
    at_cd_rec_loc         varchar(8)  not null,
    at_seg_seq_nbr        varchar(50) not null,
    at_cx_seg_seq_nbr     varchar(50) not null,
    at_pax_nbr            varchar(3),
    at_pax_nbr            at_pnr_nbr_of_pax integer,
    at_is_cx              boolean,
    at_cx_from            varchar(3),
    ca_total_revenue      double precision,
    at_cd_airline         varchar(3),
    at_cd_airport_orig    varchar(3),
    at_cd_airport_dest    varchar(3),
    at_placa              varchar(3),
    at_cd_carrier         varchar(3),
    at_cx_carrier         varchar(3),
    at_cd_airline_oper    varchar(3),
    at_route              varchar(6),
    at_market             varchar(50),
    at_cd_flight_number   integer encode az64,
    --at_dt_booking         date encode az64,
    at_dt_flight          date encode az64,
    at_dt_sale            date encode az64,
    at_family_fare        varchar(100),
    at_ca_ndo             integer encode az64,
    at_sales_channel_1    varchar(50),
    at_sales_channel_2    varchar(50),
    at_sales_channel_4    varchar(50),
    at_sales_channel_9    varchar(50),
    at_physical_channel_1 varchar(50),
    at_physical_channel_2 varchar(50),
    at_is_alliance        boolean,
    ts_creation           timestamp default getdate() encode az64,
    ts_modification       timestamp default getdate() encode az64
);