SELECT
	CAST(FF.flight_date AS DATE) as [Flight Date],
	DR.AT_DS_CLUSTER as [Cluster],
	DR.AT_DS_AIRPORT_PAIR_ORDER as [Airport Pair Order],
	DR.AT_DS_AIRPORT_PAIR as [Airport Pair],
	FF.flight_number  as [Flight Number],
	CASE  WHEN FS.irop_sched_chg IN ('I', 'M', 'S') THEN 'DISRUPTED' ELSE '' END as [DISRUPTED?],
    Count(fs.pax_nbr) as [Actual number of Pax (sold)],
    Count(case when FS.lift_status='FF' then FS.seg_seq_nbr end) as [Actual number of Pax (flown)],
	sum(COALESCE(FS.cdiscount, 0) + COALESCE(FS.reparto_Fees, 0)) as [Actual Ticket revenues Vueling],
	sum(fee.AnciRev) as [Ancillary revenues Vueling (without tickets)]

FROM
    VUELING_CALCODS.dbo.factSegment FS
    INNER JOIN VUELING_CALCODS.dbo.FactFlight FF ON FS.flight_sk=FF.flight_sk
    INNER JOIN VUELING_data_master.dbo.DIM_ROUTE DR ON FF.airport_orig=DR.AT_CD_ORIG AND FF.airport_dest=DR.AT_CD_DEST
    INNER JOIN VUELING_CALCODS.dbo.factpnr fp ON fp.rec_loc = fs.rec_loc
    INNER JOIN vueling_data_MASTER.dbo.DIM_FARE df ON df.ID_FARE=fs.ID_FARE
	left join (
        select fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR,
            sum(fee.MT_COMPANY_BASE_AMOUNT) AS AnciRev
        from VUELING_CALCODS.fees.FACT_FEE fee
            inner join Vueling_data_master.dbo.DIM_FEE_TYPE dft
                on dft.ID_FEE_TYPE = fee.ID_FEE_TYPE
        where dft.AT_DS_REVENUE_CONCEPT_1 in ('ANCILLARY','ANCILIARY','3RD PARTY ANCILIARY')
            and fee.AT_IS_AUTOGENERATED_FEE = 0
            and fee.OT_DT_END_DATE = '29991231'
        group by fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR
        ) fee on fee.AT_CD_PNR = fs.rec_loc and fee.AT_CD_PAX_NBR = fs.pax_nbr
            and fee.AT_CD_SEG_SEQ_NBR = fs.seg_seq_nbr

WHERE 1=1
    AND FF.airline_code = 'VY'
    AND cast(FF.flight_date as date) BETWEEN '{0}' AND '{1}'
	AND FS.fare_basis_nav not in ('ASSTBY0', 'ASTBYRI')
	AND ff.idstatus =1
	AND fp.sales_sk<>3
	AND df.AT_FAMILY_FARE   NOT IN  ( 'ZED High','ZED Medium','ZED LOW'  )

GROUP BY
	FF.flight_date,
	DR.AT_DS_CLUSTER,
	DR.AT_DS_AIRPORT_PAIR_ORDER,
	DR.AT_DS_AIRPORT_PAIR,
	FF.flight_number,
	CASE  WHEN FS.irop_sched_chg IN ('I', 'M', 'S') THEN 'DISRUPTED' ELSE '' END