SELECT
  CAST(DD.anyo AS VARCHAR) + RIGHT('0' + CAST(DD.week AS VARCHAR), 2) AS [Flight YearWeek (YYYYWW)],
  DD.yearmon_str as [Flight YearMonth (YYYYMM)],
  DR.AT_DS_CLUSTER as [Cluster],
  DR.AT_DS_MARKET_RANKING as [Market Ranking],
  DR.AT_DS_AIRPORT_PAIR_ORDER as [Airport Pair Order],
  sum(FFF.km*FFF.seats) as [ASK]
FROM
   VUELING_CALCODS.dbo.FactFlight  FFF
   INNER JOIN VUELING_CALCODS.dbo.FactFlight FF ON (FFF.flight_sk=FF.flight_sk)
   INNER JOIN VUELING_data_master.dbo.DIM_ROUTE DR ON (FF.airport_orig=DR.AT_CD_ORIG and FF.airport_dest=DR.AT_CD_DEST)
   INNER JOIN VUELING_CALCODS.dbo.dimDate DD ON (DD.date=FF.flight_date)
   INNER JOIN ( 
  select ID_FLIGHT
	,OT_DT_START_DATE
	,OT_DT_END_DATE
	,AT_CD_FLIGHT_NUMBER
	,AT_CD_AIRLINE_CODE
	,AT_DT_FLIGHT_DATE_UTC
	,AT_DT_FLIGHT_DATE_LOCAL_ZONE
	,AT_CD_AIRPORT_ORIG_SCH
	,AT_CD_AIRPORT_DEST_SCH
	,AT_CD_AIRPORT_ORIG_OPER
	,AT_CD_AIRPORT_DEST_OPER
	,AT_CD_LEGCD
	,ID_ROUTE
	,ID_FLIGHT_STATUS
	,AT_CD_AIRLINE_CODE_MKT
	,AT_SCHEDULE_HOUR
	,ID_AIRCRAFT
	,AT_TS_STD_UTC
	,AT_TS_STA_UTC
	,AT_TS_ATA_NAV
	,AT_TS_ATA_AIMS
	,AT_TS_ATD_NAV
	,AT_TS_ATD_AIMS
	,AT_DT_ORG_DAY
	,AT_TS_ORG_STD
	,AT_TS_STD
	,AT_TS_ORG_STA
	,AT_TS_STA
	,AT_TS_ETD
	,AT_TS_ETA
	,AT_TS_EOBT
	,AT_CD_FLIGHT_NUMBER_OPER
	,AT_ORD
	,AT_REAL_ORD
	,AT_CD_DEP_STAND
	,AT_CD_DEP_GATE
	,AT_CD_DIV_PORT
	,AT_IS_LEVEL
	,AT_IS_C3
	,AT_IS_C15
	,AT_IS_C60
	,AT_IS_C120
	,AT_IS_C180
	,AT_IS_C300
	,AT_IS_FW
	,AT_IS_OPERATIONAL
	,AT_CD_SOURCE
	,MT_SEATS
	,MT_DELAY_DEPARTURE
	,MT_BOARDED_PAX
	,AT_TS_TAKE_OFF
	,AT_TS_TAKE_DOWN
	,AT_TS_CLOSE_PAX_DOOR
	,AT_TS_CLOSE_CARGO_DOOR
	,MT_EXP_PAX
	,MT_REAL_PAX
	,MT_INF_PAX
	,MT_ST_ESCALA
	,MT_DELAY_ARR
	,MT_AT_ESCALA
	,MT_MIN_REGUL
	,MT_BAGS
	,MT_FUEL_KG
	,MT_BAGS_KG
	,MT_TOTAL_DLYT
	,MT_DISTANCE
	,MT_ASKS
	,CA_PAX_SOLD
	,CA_PAX_FLOWN
	,CA_REVENUE_TICKETS
	,CA_REVENUE_ANCIS
	,CA_YIELD
	,CA_YIELD_TICKETS
	,CA_YIELD_ANCIS
	,CA_RASK
	,CA_LID
	,CA_PAX_GROUP
	,CA_PAX_CNX
	,CA_PAX_MOVE
	,CA_PAX_STANDBY
	,CA_PAX_HOLD
	,CA_PAX_SPECIAL
	,CA_PAX_BASIC
	,CA_PAX_OPTIMA
	,CA_PAX_EXCELLENCE
	,CA_PAX_OTHER
	,CA_PAX_NOSHOW
	,CA_NUM_FEES
	,CA_NUM_FEES_SEATS
	,CA_REV_SEATS
	,CA_NUM_FEES_BAGS
	,CA_REV_BAGS
	,CA_REV_TICKET_GROUP
	,OT_CD_MD5
	,OT_TS_CREATION_DATE
	,OT_TS_MODIFICATION_DATE
	,CA_PAX_FAMILY_FARE
	,CA_PAX_TIME_FLEX
	,AT_CD_FLIGHT_NUMBER_MKT
	,AT_CD_AIRLINE_CODE_OPER
	,AT_IS_OPERATED
	,AT_DT_FLIGHT_CANCEL, ID_FLIGHT_TYPE

from VUELING_data_master.dbo.fact_flight_global
where ot_Dt_end_date='9999-12-31'
 
 
  )  FACT_FLIGHT_GLOBAL ON (FACT_FLIGHT_GLOBAL.ID_FLIGHT=FF.flight_sk)
WHERE
  FF.idStatus=1
  AND FF.airline_code = 'VY'
  AND FF.flight_number NOT BETWEEN '4000' AND '4999'
  AND case when FACT_FLIGHT_GLOBAL.ID_FLIGHT_STATUS IN(9, 21,  25, 27, 63) and (FACT_FLIGHT_GLOBAL.ID_FLIGHT_TYPE in (1,2,8) or (FACT_FLIGHT_GLOBAL.ID_FLIGHT_TYPE is null and FACT_FLIGHT_GLOBAL.at_dt_flight_date_local_zone>=cast(getdate() as date))) then 0 else 1 end  IN  ( 0 )
  AND (DD.ANYO  >= '2019' AND DD.WEEK >= 1)
GROUP BY
  DD.ANYO,
  DD.week, 
  DD.yearmon_str, 
  DR.AT_DS_CLUSTER, 
  DR.AT_DS_MARKET_RANKING,
  DR.AT_DS_AIRPORT_PAIR_ORDER