SELECT cast(FS.booking_Date as DATE) AS 'Booking_Date'
			,CASE
				WHEN FF.airport_orig > FF.airport_dest THEN concat(FF.airport_dest,FF.airport_orig)
				ELSE concat(FF.airport_orig,FF.airport_dest)
			END AS 'airport_pair_order'
			,FS.rec_loc AS 'Record Locator'
			,dcp.channel_lvl2 AS 'PH_Channel'
			,dc.channel_lvl8
			,dc.channel_lvl7
			,dc.channel_lvl5
			,dc.channel_lvl3
			,SSR.ssr_code
			,count(1) as pax
			,SUM(COALESCE(FEE.AnciRev, 0) + COALESCE(FS.cdiscount, 0) + COALESCE(FS.reparto_Fees, 0)) as 'Rev T+A'

FROM VUELING_CALCODS.dbo.Factsegment FS with (nolock)
	inner join VUELING_CALCODS.dbo.SEGMENT_SSR SSR on FS.rec_loc = SSR.rec_loc and  FS.seg_seq_nbr = SSR.seg_seq_nbr AND FS.pax_nbr = SSR.PAX_NBR
	inner join VUELING_CALCODS.dbo.FactFlight FF with (nolock) on FF.FLIGHT_SK = FS.FLIGHT_SK
	inner join VUELING_CALCODS.dbo.FactPnr FP with (nolock) on FP.rec_loc = FS.rec_loc
	inner join VUELING_VENTAS.dbo.factSegment_VentasChannel FC with (nolock) on FP.REC_LOC = FC.REC_LOC
	inner join Vueling_Ventas.dbo.DimChannel DC with (nolock) on DC.id_channel = FC.id_channel
	inner join VUELING_CALCODS.dbo.DimChannelPhysical dcp with (nolock) on dcp.id_channel_physical = FP.id_PhysicalChannel
	inner join VUELING_CALCODS.fees.FACT_FEE FFE on ffe.AT_CD_PNR = fs.rec_loc and ffe.AT_CD_PAX_NBR = fs.pax_nbr
	inner join Vueling_data_master.dbo.DIM_FEE_TYPE DFT on FFE.ID_FEE_TYPE = DFT.ID_FEE_TYPE
	left join (
        select fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR,
            sum(fee.MT_COMPANY_BASE_AMOUNT) AS AnciRev
        from VUELING_CALCODS.fees.FACT_FEE fee
            inner join Vueling_data_master.dbo.DIM_FEE_TYPE dft
                on dft.ID_FEE_TYPE = fee.ID_FEE_TYPE
        where dft.AT_DS_REVENUE_CONCEPT_1 in ('ANCILLARY','ANCILIARY','3RD PARTY ANCILIARY')
            and fee.AT_IS_AUTOGENERATED_FEE = 0
            and fee.OT_DT_END_DATE = '29991231'
        group by fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR
        ) fee on fee.AT_CD_PNR = fs.rec_loc and fee.AT_CD_PAX_NBR = fs.pax_nbr
            and fee.AT_CD_SEG_SEQ_NBR = fs.seg_seq_nbr
WHERE 1=1
		and ssr_code in ('RESA','RESI','RESO','RESV')
		and cast(FF.flight_date as DATE) >= '2023-01-01'
		and (
				(dcp.channel_lvl2 like '%B2B Agency%' and (FP.received_from like '%WWWH#BSPI%' or FP.received_from like '%TAAD#BSPI%') and DFT.AT_CD_SERVICE_TYPE = 'TASF')
				or (dcp.channel_lvl2 like '%B2B Corporate%' and DFT.AT_CD_SERVICE_TYPE = 'TASF')
			)
GROUP BY cast(FS.booking_Date as DATE)
			,CASE
				WHEN FF.airport_orig > FF.airport_dest THEN concat(FF.airport_dest,FF.airport_orig)
				ELSE concat(FF.airport_orig,FF.airport_dest)
			END
			,FS.rec_loc
			,SSR.ssr_code
			,dcp.channel_lvl2
			,dc.channel_lvl8
			,dc.channel_lvl7
			,dc.channel_lvl5
			,dc.channel_lvl3;