select
  FF.airline_code as [Operating carrier],
  year(FF.Flight_date) as [Flight Year],
  month(FF.flight_date) as [Flight Month],
  datepart(iso_week,FF.flight_date) as [Flight Week],
  year(FP.booking_date) as [Booking Year],
  month(FP.booking_date) as [Booking Month],
  datepart(iso_week,FP.booking_date) as [Booking Week],
  DR.AT_DS_MARKET_REVENUE as [Market Revenue],
  DR.AT_DS_AIRPORT_PAIR_ORDER as [Airport Pair Order],
  DC.channel_lvl4 as [PoS],
  FS.rec_loc as [Record Locator],
  DC.channel_lvl2 as [Channel lvl2],
  DC.channel_lvl3 as [Channel lvl3],
  DC.channel_lvl5 as [Channel lvl5],
  DC.channel_lvl8 as [Channel lvl8],
  case
		when sales_sk = 1 then 'Pagado'
		when sales_sk = 2 then 'Pendiente'
		when sales_sk = 3 then 'Cancelado'
		when sales_sk = 4 then 'Hold' else ''
  end as [Status],
  sum(distinct FP.nbr_of_pax) as [Sales number of Pax (Sold)],
  sum(COALESCE(FEE.AnciRev, 0) + COALESCE(FS.cdiscount, 0) + COALESCE(FS.reparto_Fees, 0)) as [Revenue T+A]
from dbo.factsegment fs
	inner join dbo.factflight ff on ff.flight_sk = fs.flight_sk
	inner join dbo.factpnr fp on fp.rec_loc = fs.rec_loc
	inner join vueling_ventas.dbo.factSegment_VentasChannel fsvc on fp.REC_LOC = fsvc.REC_LOC
	inner join vueling_ventas.dbo.dimchannel dc on fsvc.id_channel=dc.id_channel
	inner join vueling_data_master.dbo.dim_route DR on dr.AT_CD_ORIG = FF.airport_orig and dr.AT_CD_DEST = FF.airport_dest
    left join (
        select fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR,
            sum(fee.MT_COMPANY_BASE_AMOUNT) AS AnciRev
        from fees.FACT_FEE fee
            inner join vueling_data_master.dbo.DIM_FEE_TYPE dft
                on dft.ID_FEE_TYPE = fee.ID_FEE_TYPE
        where dft.AT_DS_REVENUE_CONCEPT_1 in ('ANCILLARY','ANCILIARY','3RD PARTY ANCILIARY')
            and fee.AT_IS_AUTOGENERATED_FEE = 0
            and fee.OT_DT_END_DATE = '29991231'
        group by fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR
        ) fee on fee.AT_CD_PNR = fs.rec_loc and fee.AT_CD_PAX_NBR = fs.pax_nbr
            and fee.AT_CD_SEG_SEQ_NBR = fs.seg_seq_nbr
where
	FF.idStatus=1
	and year(FF.Flight_date) >=  2019
	and FF.airline_code = 'VY'
	and FF.airline_code = FF.mktCarrierCode
	and DC.channel_lvl2 in ('VY TTOO CUPOS','CHARTER')
	and FP.sales_sk <> 3
	and channel_lvl8 is NULL
group by
  FF.airline_code,
  year(FF.Flight_date),
  month(FF.flight_date),
  datepart(iso_week,FF.flight_date),
  year(FP.booking_date),
  month(FP.booking_date),
  datepart(iso_week,FP.booking_date),
  DR.AT_DS_MARKET_REVENUE,
  DR.AT_DS_AIRPORT_PAIR_ORDER,
  DC.channel_lvl4,
  FS.rec_loc,
  DC.channel_lvl2,
  DC.channel_lvl3,
  DC.channel_lvl5,
  DC.channel_lvl8,
  case
		when sales_sk = 1 then 'Pagado'
		when sales_sk = 2 then 'Pendiente'
		when sales_sk = 3 then 'Cancelado'
		when sales_sk = 4 then 'Hold' else ''
  end;