select
	ffe.AT_CD_PNR,
	ffe.OT_TS_CREATION_DATE as creation_bundle,
	count(1) as num_bundle,
	 dft.AT_DS_REVENUE_CONCEPT_3 as bundle_type,
	cast(SUM(COALESCE(FEE.AnciRev, 0)) as money) as bundle_revenue,
	case
		when dcp.AT_CHANNEL_LVL1 = 'API Mobile' and dcp.AT_CHANNEL_LVL2 = 'MOBILE' then 'mobile'
        when dcp.AT_CHANNEL_LVL1 = 'WEB' then 'desktop'
    end as plataforma,
    AT_CD_SERVICE_TYPE as FeeCode, --se añade campo
	FF.route_m as Route, --se añade campo
	case when ffe.at_is_post_booking = 1 then 'Manage my booking' else 'Booking Flow' end as flujo
from
	Vueling_calcods.fees.fact_fee ffe
	inner join vueling_data_master.dbo.dim_fee_type dft on dft.id_fee_type = ffe.id_fee_type
	inner join Vueling_data_master.dbo.DIM_CHANNEL_PHYSICAL_FEE dcp ON dcp.ID_CHANNEL_PHYSICAL_FEE = ffe.id_channel_physical
	inner join (
        select fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR,
            sum(fee.MT_COMPANY_BASE_AMOUNT) AS AnciRev
        from VUELING_CALCODS.fees.FACT_FEE fee
            inner join Vueling_data_master.dbo.DIM_FEE_TYPE dft
                on dft.ID_FEE_TYPE = fee.ID_FEE_TYPE
        where dft.AT_DS_REVENUE_CONCEPT_1 in ('ANCILLARY','ANCILIARY','3RD PARTY ANCILIARY')
            and fee.AT_IS_AUTOGENERATED_FEE = 0
            and fee.OT_DT_END_DATE = '29991231'
        group by fee.AT_CD_PNR, fee.AT_CD_PAX_NBR, fee.AT_CD_SEG_SEQ_NBR
        ) FEE on fee.AT_CD_PNR = ffe.AT_CD_PNR and fee.AT_CD_PAX_NBR = ffe.AT_CD_PAX_NBR and fee.AT_CD_SEG_SEQ_NBR = ffe.AT_CD_SEG_SEQ_NBR
    inner join Vueling_calcods.dbo.factflight FF on FF.flight_sk = FFE.id_flight --se añade inner join
where
	cast(ffe.OT_TS_CREATION_DATE as date) = cast(getdate() as date)
	and AT_CD_SERVICE_TYPE in ('VCB1', 'VCB2', 'VCB3')
group by
	ffe.AT_CD_PNR,
	ffe.OT_TS_CREATION_DATE,
	dft.AT_DS_REVENUE_CONCEPT_3,
	case
		when dcp.AT_CHANNEL_LVL1 = 'API Mobile' and dcp.AT_CHANNEL_LVL2 = 'MOBILE' then 'mobile'
        when dcp.AT_CHANNEL_LVL1 = 'WEB' then 'desktop'
    end,
    AT_CD_SERVICE_TYPE, --se añade campo
	FF.route_m, --se añade campo
	case when ffe.at_is_post_booking = 1 then 'Manage my booking' else 'Booking Flow' end;