apiVersion: v1
kind: ServiceAccount
metadata:
  name: "${service_account}"
  namespace: "${eks_namespace}"
  labels:
    app.kubernetes.io/managed-by: eksctl
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${account}:role/${team}-${product}-${project}-r
